StoredXSS Demo/Models/Person.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace StoredXSS_Demo.Models
{
    public class Person
    {
        public int Id { get; set; }
        public string FullName { get; set; }

        public string Job { get; set; }
    }
}

StoredXSS Demo/Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Data.SqlClient;
using StoredXSS_Demo.Models;
using System.Data;
using System.Web.Configuration;

namespace StoredXSS_Demo.Controllers
{
    public class PersonController : Controller
    {
        //
        // GET: /Person/
        SqlConnection con = new SqlConnection(WebConfigurationManager.ConnectionStrings["U001"].ConnectionString);
        DataTable dt = new DataTable();

        public ActionResult Index()
        {
            SqlDataAdapter da = new SqlDataAdapter("select * from Person",con);
            da.Fill(dt);
            return View(dt);
        }

        //
        // GET: /Person/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Person/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Person/Create
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult Create(Person p)
        {
            SqlCommand cmd = new SqlCommand(" insert into Person (FullName,Job) values ('"+p.FullName+"','"+p.Job+"') ",con);
            con.Open();
            cmd.ExecuteNonQuery();
            con.Close();
            return RedirectToAction("Index");
            
        }

        //
        // GET: /Person/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /Person/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /Person/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Person/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

StoredXSS Demo/Controllers/ReflectedXSSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StoredXSS_Demo.Controllers
{
    public class ReflectedXSSController : Controller
    {
        //
        // GET: /ReflectedXSS/
        [ValidateInput(false;)]
        public ActionResult Index()
        {
            if (Request.QueryString["txtsearch"] != null)
            {
                //unvalidated
                ViewBag.results = "Search Results For : " + Request.QueryString["txtsearch"];

            }
            return View();
        }

        //
        // GET: /ReflectedXSS/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /ReflectedXSS/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /ReflectedXSS/Create

        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /ReflectedXSS/Edit/5

        public ActionResult Edit(int id)
        {
            return View();
        }

        //
        // POST: /ReflectedXSS/Edit/5

        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        //
        // GET: /ReflectedXSS/Delete/5

        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /ReflectedXSS/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

StoredXSS Demo/Views/Person/Create.cshtml
@model StoredXSS_Demo.Models.Person

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
   

    <fieldset>
        <legend>Person</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.FullName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.FullName)
           
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Job)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Job)
        
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
   @*
    @Scripts.Render("~/bundles/jqueryval")
        @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
        @Html.ValidationMessageFor(model => model.FullName)
           @Html.ValidationMessageFor(model => model.Job)
*@ 
}

StoredXSS Demo/Views/Person/Index.cshtml
@using System.Data

@model DataTable

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
</head>
<body>
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
    <table>
        <tr>
            <th>
               FullName
            </th>
            <th>
              Job
            </th>
          
        </tr>
    
    @foreach (DataRow row in Model.Rows) {
        <tr>
            <td>
                @Html.Raw(row["FullName"])
            </td>
            <td>
                @Html.Raw(row["Job"])
            </td>
           
        </tr>
    }
    
    </table>
</body>
</html>

StoredXSS Demo/Views/ReflectedXSS/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Search</title>
</head>
@using (Html.BeginForm("Index","ReflectedXSS", FormMethod.Get))
{
    <h5>@Html.Raw( ViewBag.results)</h5>
        <h3>search here </h3><input type="text" name="txtsearch" />
        <input type="submit" value="search" />
        
  }